In [15]:
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn
import kagglehub
import matplotlib.pyplot as plt

In [16]:

# Download latest version
eu = pd.read_csv('/Users/ebrahimnouri/code/PycharmProjects/MS_AI/data/eurusd_hour.csv')

eu.drop('Date', axis='columns', inplace=True)
eu.head()

,Time,BO,BH,BL,BC,BCh,AO,AH,AL,AC,ACh
0,00:00,1.2852,1.2852,1.2840,1.2844,-0.0008,1.2854,1.2854,1.2842,1.2846,-0.0008
1,01:00,1.2844,1.2848,1.2839,1.2842,-0.0002,1.2846,1.2850,1.2841,1.2844,-0.0002
2,02:00,1.2843,1.2854,1.2841,1.2851,0.0008,1.2845,1.2856,1.2843,1.2853,0.0008
3,03:00,1.2851,1.2859,1.2850,1.2851,0.0000,1.2853,1.2861,1.2852,1.2853,0.0000
4,04:00,1.2852,1.2859,1.2849,1.2855,0.0003,1.2854,1.2861,1.2851,1.2857,0.0003

In [17]:
eu.tail()

,Time,BO,BH,BL,BC,BCh,AO,AH,AL,AC,ACh
93079,18:00,1.08620,1.08851,1.08611,1.08713,0.00093,1.08660,1.08865,1.08640,1.08726,0.00066
93080,19:00,1.08711,1.08823,1.08659,1.08748,0.00037,1.08725,1.08837,1.08675,1.08760,0.00035
93081,20:00,1.08747,1.08788,1.08691,1.08708,-0.00039,1.08758,1.08810,1.08706,1.08808,0.00050
93082,21:00,1.08708,1.08740,1.08699,1.08714,0.00006,1.08808,1.08814,1.08763,1.08766,-0.00042
93083,22:00,1.08728,1.08760,1.08727,1.08743,0.00015,1.08756,1.08779,1.08749,1.08760,0.00004

In [18]:
eu.shape, eu.info()

<class 'pandas.DataFrame'>
RangeIndex: 93084 entries, 0 to 93083
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    93084 non-null  str
 1   BO      93084 non-null  float64
 2   BH      93084 non-null  float64
 3   BL      93084 non-null  float64
 4   BC      93084 non-null  float64
 5   BCh     93084 non-null  float64
 6   AO      93084 non-null  float64
 7   AH      93084 non-null  float64
 8   AL      93084 non-null  float64
 9   AC      93084 non-null  float64
 10  ACh     93084 non-null  float64
dtypes: float64(10), str(1)
memory usage: 7.8 MB

((93084, 11), None)

In [19]:
eu.isna().sum()

Time    0
BO      0
BH      0
BL      0
BC      0
BCh     0
AO      0
AH      0
AL      0
AC      0
ACh     0
dtype: int64

In [20]:
eu.describe()

,BO,BH,BL,BC,BCh,AO,AH,AL,AC,ACh
count,93084.000000,93084.000000,93084.000000,93084.000000,9.308400e+04,93084.000000,93084.000000,93084.000000,93084.000000,93084.000000
mean,1.265734,1.266755,1.264736,1.265733,-8.928495e-07,1.265900,1.266917,1.264897,1.265899,-0.000001
std,0.126894,0.127060,0.126722,0.126892,1.544143e-03,0.126891,0.127053,0.126715,0.126891,0.001546
min,1.035530,1.036970,1.033950,1.035550,-2.505000e-02,1.035660,1.037100,1.034090,1.035680,-0.024950
25%,1.139878,1.140728,1.139130,1.139880,-6.000000e-04,1.140050,1.140890,1.139300,1.140048,-0.000590
50%,1.274100,1.275315,1.272955,1.274105,1.000000e-05,1.274280,1.275490,1.273150,1.274290,0.000000
75%,1.357615,1.358770,1.356533,1.357630,6.000000e-04,1.357770,1.358920,1.356673,1.357770,0.000600
max,1.601310,1.603840,1.599200,1.601390,3.022000e-02,1.601400,1.603930,1.599290,1.601480,0.030430

In [21]:
plt.figure(figsize=(15,6))
plt.plot(eu.close)
plt.title('Euro vs USD')
plt.legend()
plt.show()

AttributeError: 'DataFrame' object has no attribute 'close'

In [ ]:
plt.figure(figsize=(15,6))
plt.plot(eu.volume)
plt.title('Euro vs USD')
plt.legend()
plt.show()

In [ ]:
#box plot for open, high, low , close
eu.drop('volume', axis=1).boxplot()

In [ ]:
sns.heatmap(eu.corr())

In [ ]:
eu.plot(y=['volume'],figsize=(25,10))

In [ ]:
eu.resample('Y').mean().plot.bar(y=['volume'], figsize=[25,10])

In [ ]:
eu.resample('Y').mean().plot.bar(y=['close'], figsize=[25,10])

In [ ]:
ax = eu.groupby(['close'])['volume'].last().sort_values(ascending=False).head(10).sort_values().plot(kind='barh');
ax.set_xlabel("volume");

In [ ]:
from pandas.plotting import lag_plot

lag_plot(eu['volume'].tail(500))

In [ ]:
from pandas.plotting import lag_plot

lag_plot(eu['close'].tail(500))

In [ ]:
eu.iloc[:100].plot(y=['open', 'high', 'low', 'close'], figsize=(25,10))

In [ ]:
for itr in eu.columns:
    eu.plot(y=[itr], figsize=(25,10))